export const UserTypes = {
    // GET Users
    SUCCESS_GET_USERS: '@user/SUCCESS_GET_USERS',
    REQUEST_GET_USERS : '@user/REQUEST_GET_USERS',
    GET_USERS_ERROR: '@user/GET_USERS_ERROR',
    RESET_SUCCESS_GET_USERS: '@user/RESET_SUCCESS_GET_USERS',
    
    // Create new user
    REQUEST_CREATE_NEW_USER : '@user/REQUEST_CREATE_NEW_USER',
    CREATE_NEW_USER_ERROR: '@user/CREATE_NEW_USER_ERROR',

    // Create new farm user
    REQUEST_CREATE_NEW_FARM_USER : '@user/REQUEST_CREATE_NEW_FARM_USER',
    CREATE_NEW_FARM_USER_ERROR: '@user/CREATE_NEW_FARM_USER_ERROR',

    SUCCESS_CREATE_NEW_USER: '@user/SUCCESS_CREATE_NEW_USER',
    RESET_SUCCESS_CREATE_NEW_USER: '@user/RESET_SUCCESS_CREATE_NEW_USER',
     
    SUCCESS_UPDATE_USER_DATA: '@user/SUCCESS_UPDATE_USER_DATA',
    RESET_SUCCESS_UPDATE_USER_DATA: '@user/RESET_SUCCESS_UPDATE_USER_DATA',
     
    // Update user data
    REQUEST_UPDATE_USER_DATA : '@user/REQUEST_UPDATE_USER_DATA',
    UPDATE_USER_DATA_ERROR: '@user/UPDATE_USER_DATA_ERROR',
    
    // Update farm user data
    REQUEST_UPDATE_FARM_USER_DATA : '@user/REQUEST_UPDATE_FARM_USER_DATA',
    UPDATE_FARM_USER_DATA_ERROR: '@user/UPDATE_FARM_USER_DATA_ERROR',

    // GET farm data
    SUCCESS_GET_FARM_DATA: '@user/SUCCESS_GET_FARM_DATA',
    REQUEST_GET_FARM_DATA : '@user/REQUEST_GET_FARM_DATA',
    GET_FARM_DATA_ERROR: '@user/GET_FARM_DATA_ERROR',
     
    // Update General Information
    SUCCESS_UPDATE_GENERAL_INFO: '@user/SUCCESS_UPDATE_GENERAL_INFO',
    RESET_SUCCESS_UPDATE_GENERAL_INFO: '@user/RESET_SUCCESS_UPDATE_GENERAL_INFO',
    REQUEST_UPDATE_GENERAL_INFO : '@user/REQUEST_UPDATE_GENERAL_INFO',
    UPDATE_GENERAL_INFO_ERROR: '@user/UPDATE_GENERAL_INFO_ERROR',

    NO_USERS_COLLECTION: '@task/NO_USERS_COLLECTION',
}
