export const NotificationTypes = {
    SUCCESS_GET_NOTIFICATIONS: '@notification/SUCCESS_GET_NOTIFICATIONS',
    REQUEST_GET_NOTIFICATIONS : '@notification/REQUEST_GET_NOTIFICATIONS',
    GET_NOTIFICATIONS_ERROR : '@notification/GET_NOTIFICATIONS_ERROR',
}
