export const AuthTypes = {
    SIGNIN: '@auth/SIGNIN',
    SIGNUP: '@auth/SIGNUP',
    SIGNOUT: '@auth/SIGNOUT',

    AUTH_ERROR: '@auth/AUTH_ERROR',
    
    REQUEST_SIGNIN_EMAIL_PASSWORD: '@auth/REQUEST_SIGNIN_EMAIL_PASSWORD',

    REQUEST_SIGNUP_EMAIL_PASSWORD: '@auth/REQUEST_SIGNUP_EMAIL_PASSWORD',
    RESET_SIGNUP_ID: '@user/RESET_SIGNUP_ID',

    REQUEST_GET_CURRENT_USER: '@auth/REQUEST_GET_CURRENT_USER',
    SUCCESS_GET_CURRENT_USER: '@auth/SUCCESS_GET_CURRENT_USER',
    RESET_SUCCESS_GET_CURRENT_USER: '@auth/RESET_SUCCESS_GET_CURRENT_USER',
}
