export const TaskTypes = {
    SUCCESS_GET_TASKS: '@task/SUCCESS_GET_TASKS',
    REQUEST_GET_TASKS : '@task/REQUEST_GET_TASKS',
    GET_TASKS_ERROR: '@task/GET_TASKS_ERROR',
    
    SUCCESS_CREATE_NEW_TASK: '@task/SUCCESS_CREATE_NEW_TASK',
    REQUEST_CREATE_NEW_TASK : '@task/REQUEST_CREATE_NEW_TASK',
    CREATE_NEW_TASK_ERROR: '@task/CREATE_NEW_TASK_ERROR',
    RESET_SUCCESS_CREATE_NEW_TASK: '@task/RESET_SUCCESS_CREATE_NEW_TASK',

    SUCCESS_EDIT_TASK: '@task/SUCCESS_EDIT_TASK',
    REQUEST_EDIT_TASK : '@task/REQUEST_EDIT_TASK',
    EDIT_TASK_ERROR: '@task/EDIT_TASK_ERROR',
    RESET_SUCCESS_EDIT_TASK: '@task/RESET_SUCCESS_EDIT_TASK',

    SUCCESS_DELETE_TASK: '@task/SUCCESS_DELETE_TASK',
    REQUEST_DELETE_TASK : '@task/REQUEST_DELETE_TASK',
    DELETE_TASK_ERROR: '@task/DELETE_TASK_ERROR',
    RESET_SUCCESS_DELETE_TASK: '@task/RESET_SUCCESS_DELETE_TASK',
}
