export const HerdTypes = {
    SUCCESS_GET_HERDS: '@herd/SUCCESS_GET_HERDS',
    REQUEST_GET_HERDS : '@herd/REQUEST_GET_HERDS',
    GET_HERDS_ERROR: '@herd/GET_HERDS_ERROR',
    
    SUCCESS_ADD_NEW_HERD: '@herd/SUCCESS_ADD_NEW_HERD',
    RESET_SUCCESS_ADD_NEW_HERD: '@herd/RESET_SUCCESS_ADD_NEW_HERD',
    REQUEST_ADD_NEW_HERD : '@herd/REQUEST_ADD_NEW_HERD',
    ADD_NEW_HERD_ERROR: '@herd/ADD_NEW_HERD_ERROR',
    
    SUCCESS_EDIT_HERD_DATA: '@herd/SUCCESS_EDIT_HERD_DATA',
    RESET_SUCCESS_EDIT_HERD_DATA: '@herd/RESET_SUCCESS_EDIT_HERD_DATA',
    REQUEST_EDIT_HERD_DATA : '@herd/REQUEST_EDIT_HERD_DATA',
    EDIT_HERD_DATA_ERROR: '@herd/EDIT_HERD_DATA_ERROR',
    
    SUCCESS_DELETE_HERD: '@task/SUCCESS_DELETE_HERD',
    REQUEST_DELETE_HERD : '@task/REQUEST_DELETE_HERD',
    DELETE_HERD_ERROR: '@task/DELETE_HERD_ERROR',
    RESET_SUCCESS_DELETE_HERD: '@task/RESET_SUCCESS_DELETE_HERD',

    NO_HERDS_COLLECTION: '@task/NO_HERDS_COLLECTION',
}
